// This is an AI-powered code generated by Firebase Studio.
'use server';

/**
 * @fileOverview This file defines a Genkit flow for generating image prompts based on content.
 *
 * - generateImagePrompts - A function that generates image prompts for given content.
 * - GenerateImagePromptsInput - The input type for the generateImagePrompts function.
 * - GenerateImagePromptsOutput - The return type for the generateImagePrompts function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateImagePromptsInputSchema = z.object({
  content: z.string().describe('The content to generate image prompts for.'),
  platform: z
    .enum(['wordpress', 'instagram', 'facebook'])
    .describe('The platform for which the image prompts are being generated.'),
  imagePromptFrequency: z
    .number()
    .optional()
    .describe(
      'The frequency (in words) at which to generate image prompts for wordpress. Only applicable for wordpress.'
    ),
});
export type GenerateImagePromptsInput = z.infer<typeof GenerateImagePromptsInputSchema>;

const GenerateImagePromptsOutputSchema = z.object({
  imagePrompts: z.array(z.string()).describe('The generated image prompts.'),
});
export type GenerateImagePromptsOutput = z.infer<typeof GenerateImagePromptsOutputSchema>;

export async function generateImagePrompts(
  input: GenerateImagePromptsInput
): Promise<GenerateImagePromptsOutput> {
  return generateImagePromptsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateImagePromptsPrompt',
  input: {schema: GenerateImagePromptsInputSchema},
  output: {schema: GenerateImagePromptsOutputSchema},
  prompt: `You are an expert content creator who generates image prompts for blog posts and social media updates.

  You will generate image prompts based on the content provided.

  If the platform is wordpress, you will generate image prompts every {{imagePromptFrequency}} words.

  The content is: {{{content}}}

  The platform is: {{{platform}}}
  `,
});

const generateImagePromptsFlow = ai.defineFlow(
  {
    name: 'generateImagePromptsFlow',
    inputSchema: GenerateImagePromptsInputSchema,
    outputSchema: GenerateImagePromptsOutputSchema,
  },
  async input => {
    let imagePromptFrequency = 200;
    if (input.platform === 'wordpress' && input.imagePromptFrequency) {
      imagePromptFrequency = input.imagePromptFrequency;
    }

    const promptInput = {
      ...input,
      imagePromptFrequency,
    };

    const {output} = await prompt(promptInput);
    return output!;
  }
);
