
export type Platform = "Wordpress" | "Instagram" | "Facebook";
export type ContentStatus = "Draft" | "Scheduled" | "Published";

export interface ResearchLinkItem {
  id: string; // Client-generated ID (e.g., URL or timestamp based)
  title: string;
  url: string;
  summary: string; // Can be a detailed account/transcription from the link
  abntCitation?: string; // Optional, might be generated by AI or manually
}

export interface ManualReferenceItem {
  id: string;
  title?: string;
  content: string;
  createdAt: string; // ISO date string
}

export interface ThemeSuggestion {
  id: string;
  userInputTopic: string;
  title: string;
  description: string;
  keywords?: string[]; // Added keywords
  generatedAt: string;
  researchLinks?: ResearchLinkItem[];
  manualReferences?: ManualReferenceItem[];
}

export interface ContentItem {
  id: string;
  title: string;
  topic: string;
  platform: Platform;
  content: string;
  imagePrompts: string[];
  wordCount?: number;
  imagePromptFrequency?: number;
  hashtags?: string[];
  status: ContentStatus;
  createdAt: string;
  updatedAt: string;
  scheduledAt?: string;
  // Store references used for generating this content item
  referenceLinksUsed?: Array<{ title: string; url: string; summary: string; abntCitation?: string }>;
  manualReferencesUsed?: Array<{ title?: string; content: string }>;
}

export interface AppSettings {
  openAIKey: string;
  openAIAgentId?: string;
  outputLanguage?: string;
  perplexityApiKey?: string;
}

// For passing references to the content generation flow
export interface ReferenceMaterial {
  url: string;
  summary: string; // This is the detailed text / "transcription"
  title: string;
}

export interface GenerateContentForPlatformInput {
  platform: Platform;
  topic: string;
  wordCount?: number;
  apiKey: string;
  agentId?: string;
  outputLanguage?: string;
  referenceItems?: ReferenceMaterial[];
  manualReferenceTexts?: string[]; // Texts from manually added references
}

export interface GenerateContentForPlatformOutput {
  content: string;
  imagePrompt: string;
}
